- hosts: all
  tasks:
    - name: Ensure group "ansible-worker" exists
      ansible.builtin.group:
        name: ansible-worker
        state: present
      become: yes

    - name: add user ansible-worker
      ansible.builtin.user:
        name: ansible-worker
        shell: /bin/bash
        group: ansible-worker
        shell: /bin/bash
        groups: www-data
        append: yes
      become: yes

    - name: Copy SSH keys ansible-worker
      ansible.builtin.copy:
        src: ssh_keys/
        dest: /home/ansible-worker/.ssh/
        owner: ansible-worker
        group: ansible-worker
        mode: 0600
      become: yes

    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes

    - name: Clone repository iphilka
      ansible.builtin.git:
        repo: "https://github.com/iphilka/stud-template.git"
        dest: "/home/ansible-worker/www/stud-template"
        update: no
        clone: yes
      become: yes

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
    
    - name: Update html
      ansible.builtin.copy:
        src: index.html
        dest: /home/ansible-worker/www/stud-template/index.html
        owner: ansible-worker
        group: www-data
        mode: u=rw,g=r,o=r
      become: yes 

    - name: ansible-worker and www-data
      ansible.builtin.shell:
        cmd: usermod -a -G ansible-worker www-data
      become: yes
      
    - name: Update nginx config
      ansible.builtin.copy:
        src: ansible.iphilka.ru.conf
        dest: /etc/nginx/sites-available/ansible.iphilka.ru.conf
      become: yes 

    - name: Enable  ansible.iphilka.ru.conf
      ansible.builtin.shell:
        cmd:  ln -s /etc/nginx/sites-available/ansible.iphilka.ru.conf /etc/nginx/sites-enabled/ansible.iphilka.ru.conf
      become: yes  

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
